# Site settings
title: Nguyen Minh Tam
email: minhtamck4@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Somethings need to note.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://codepi.xyz" # the base hostname & protocol for your site
twitter_username: MinhTam70910140
github_username:  MinhTamCK

# Build settings
markdown: kramdown
